const services={
 "dynamics-365-crm":{n:"01",title:"Dynamics 365 CRM",em:"Make every customer interaction count.",intro:"Connect sales, service and customer intelligence around a shared view of the relationship—designed for the people doing the work.",outcomes:["Connected sales and service","Customer journeys that feel joined up","Actionable relationship intelligence"],deliver:["Discovery & solution design","Sales, service & Dataverse delivery","Integration, migration & adoption"],tech:["Dynamics 365 Sales","Customer Service","Customer Insights","Dataverse","Power Automate"]},
 "power-apps":{n:"02",title:"Power Apps",em:"Useful apps. Built around real work.",intro:"Give teams governed, fit-for-purpose business applications without asking them to live in spreadsheets, inboxes and disconnected tools.",outcomes:["Faster business processes","Governed low-code delivery","Apps people adopt"],deliver:["Process mapping","Canvas & model-driven apps","ALM and Centre of Excellence enablement"],tech:["Power Apps","Dataverse","Power Automate","Power Fx","Microsoft 365"]},
 "power-pages":{n:"03",title:"Power Pages",em:"Digital experiences with context.",intro:"Create secure portals for customers, partners and communities, connected to the systems and information behind every request.",outcomes:["Secure self-service","A clearer digital front door","Connected customer journeys"],deliver:["Portal strategy & UX","Dataverse integration","Identity, security & rollout"],tech:["Power Pages","Dataverse","Microsoft Entra ID","Dynamics 365","Azure"]},
 "azure":{n:"04",title:"Azure",em:"Cloud foundations that move with you.",intro:"Build resilient, secure Azure platforms and applications that make data, integration and innovation easier to scale.",outcomes:["Resilient cloud platforms","Better connected systems","Clearer operational control"],deliver:["Architecture & landing zones","Cloud-native delivery","DevOps, security & optimisation"],tech:["Azure","Azure DevOps","Azure Functions","API Management","Azure OpenAI"]},
 "ai-ml":{n:"05",title:"AI, ML & Agents",em:"Intelligence designed for accountable work.",intro:"Move from AI experimentation to useful, governed assistants, agents and machine-learning solutions connected to your trusted data.",outcomes:["Practical AI adoption","Agents with human oversight","Trusted decisions at scale"],deliver:["AI opportunity design","Copilot, Claude & Azure AI integration","Responsible AI guardrails"],tech:["Azure AI","Azure OpenAI","Copilot Studio","Claude","Machine Learning"]},
 "sharepoint":{n:"06",title:"SharePoint",em:"Knowledge people can find and use.",intro:"Turn SharePoint into a clear, governed knowledge and collaboration environment that supports the way teams actually work.",outcomes:["Better knowledge discovery","Governed collaboration","A stronger Microsoft 365 foundation"],deliver:["Information architecture","Intranets & knowledge hubs","Migration, governance & adoption"],tech:["SharePoint","Microsoft Teams","Microsoft 365","Copilot","Power Automate"]},
 "dotnet-apps":{n:"07",title:".NET Apps",em:"Business applications built to endure.",intro:"Engineer secure, scalable .NET applications that fit naturally into your Microsoft estate and evolve with the business.",outcomes:["Reliable business software","Modern integration patterns","A maintainable application estate"],deliver:["Solution architecture","API & application development","Modernisation & managed improvement"],tech:[".NET","ASP.NET Core","C#","Azure","SQL Server"]},
 "react":{n:"08",title:"React",em:"Front ends people enjoy using.",intro:"Design and build polished, responsive React experiences for complex business journeys, internal platforms and customer products.",outcomes:["Fast, intuitive experiences","Reusable interface systems","Responsive digital products"],deliver:["Product UX & UI","React application delivery","Design systems & accessibility"],tech:["React","TypeScript","Next.js","REST APIs","Azure"]},
 "pcf-components":{n:"09",title:"PCF Components",em:"Make Dynamics work like your business.",intro:"Extend Dynamics 365 and Power Apps with purpose-built controls that make data, workflows and everyday interactions more useful.",outcomes:["A better user experience","Purpose-built controls","More capable model-driven apps"],deliver:["Control discovery","PCF design & development","Deployment and support"],tech:["Power Apps Component Framework","TypeScript","Dataverse","Dynamics 365","Azure DevOps"]},
 "power-bi":{n:"10",title:"Power BI",em:"Insight that changes the next decision.",intro:"Connect trusted data to clear reporting and decision-making, so leaders and teams can see what matters and act with confidence.",outcomes:["A trusted view of performance","Self-service insight with governance","Data stories people act on"],deliver:["Data & reporting strategy","Semantic models & dashboards","Fabric and governance enablement"],tech:["Power BI","Microsoft Fabric","DAX","Azure Data","Dataverse"]},
 "web-applications":{n:"11",title:"Web Applications",em:"Digital products built for real outcomes.",intro:"Create secure, high-performing web applications and portals that combine a refined customer experience with solid enterprise engineering.",outcomes:["Digital journeys that convert","Secure scalable platforms","One connected customer experience"],deliver:["Product strategy & UX","Web application engineering","Integration, release & evolution"],tech:["React",".NET","Azure","APIs","Dynamics 365"]},
 "data-integration":{n:"12",title:"Data & Integration",em:"Bring the business into one flow.",intro:"Connect applications, data and events so teams work with a shared picture rather than a growing collection of hand-offs.",outcomes:["Less manual rework","Reliable business data","Connected end-to-end processes"],deliver:["Integration architecture","API and event-driven delivery","Data platform & quality design"],tech:["Azure Integration Services","API Management","Logic Apps","Microsoft Fabric","Dataverse"]},
 "security-governance":{n:"13",title:"Security & Governance",em:"Innovation with the right guardrails.",intro:"Put practical control around Microsoft cloud, Power Platform and AI so teams can move quickly without losing trust, visibility or accountability.",outcomes:["Safer adoption at scale","Clear ownership and controls","A platform ready for growth"],deliver:["Governance assessment","Security & environment strategy","Operating model and standards"],tech:["Microsoft Entra ID","Power Platform Admin Center","Microsoft Purview","Defender for Cloud","Azure Policy"]},
 "managed-services":{n:"14",title:"Adoption & Managed Services",em:"Keep the progress moving.",intro:"Support the people, platforms and continuous improvement work that turns a successful launch into sustained business value.",outcomes:["Stronger adoption","Reliable operations","Continuous improvement"],deliver:["Adoption & enablement","Platform support and optimisation","Roadmaps, releases and advisory"],tech:["Azure Monitor","Power Platform","Dynamics 365","Microsoft 365","DevOps"]}
};
const related=Object.entries(services).filter(([slug])=>slug!==document.body.dataset.service).slice(0,3);
function navigation(){return `<div class="announcement"><div class="shell">Engineering AI-first enterprise solutions <b>•</b> Microsoft, data & intelligent automation</div></div><header class="site-header"><div class="shell nav-wrap"><a class="brand" href="/"><img src="https://ampersyn.com/assets/ampersyn-logo.png" alt="Ampersyn logo">Ampersyn</a><nav class="nav"><a href="/">Home</a><details class="services-menu"><summary>Services</summary><div class="services-flyout">${Object.entries(services).map(([slug,s])=>`<a href="/services/${slug}/">${s.title}</a>`).join('')}</div></details><a href="/#agentic-ai">AI & Agents</a><a href="/about-us/">About us</a><a class="nav-cta" href="/#contact">Start a conversation ↗</a></nav></div></header>`}
function footer(){return `<footer class="footer"><div class="shell footer-top"><div><a class="brand" href="/"><img src="https://ampersyn.com/assets/ampersyn-logo.png" alt="Ampersyn logo">Ampersyn</a><p style="margin-top:12px">Engineering intelligent business transformation through Microsoft cloud, data and AI.</p><a class="footer-phone" href="tel:+918897648544"><b>●</b>+91-8897648544</a></div><p>© 2026 Ampersyn. All rights reserved.</p></div></footer>`}
function servicePage(s){return `${navigation()}<main><section class="hero"><div class="shell"><p class="eyebrow"><i></i>Services / ${s.n}</p><h1>${s.title}.<br><em>${s.em}</em></h1><p>${s.intro}</p><div class="hero-meta"><span>Business-first</span><span>Microsoft-native</span><span>Built to evolve</span></div></div></section><section class="section"><div class="shell"><div class="section-title"><p class="eyebrow"><i></i>What changes</p><div><h2>Technology should make the work <em>clearer.</em></h2><p>We combine business context, experience design and hands-on engineering to make this capability useful from the first release.</p></div></div><div class="work-grid">${s.outcomes.map((x,i)=>`<article class="work-card"><span>0${i+1}</span><h3>${x}</h3><p>Designed around the outcome that matters to your customers, teams and operations.</p></article>`).join('')}</div></div></section><section class="section dark"><div class="shell"><div class="section-title"><p class="eyebrow"><i></i>How we deliver</p><div><h2>Focused work. <em>Practical momentum.</em></h2><p>Each engagement is shaped around your starting point, but follows a clear path from understanding to confident adoption.</p></div></div><div class="delivery"><h3>What the work includes.</h3><div class="delivery-list">${s.deliver.map((x,i)=>`<div><span>0${i+1}</span><b>${x}</b></div>`).join('')}</div></div></div></section><section class="technology"><div class="shell"><h2>The platform <em>around the work.</em></h2><div class="technology-list">${s.tech.map(x=>`<span>${x}</span>`).join('')}</div></div></section><section class="related"><div class="shell"><h2>Explore related services.</h2><div class="related-grid">${related.map(([slug,x])=>`<a href="/services/${slug}/"><span>Service ${x.n}</span><b>${x.title} ↗</b></a>`).join('')}</div></div></section><section class="cta"><div class="shell cta-grid"><h2>Bring us the challenge. <em>We’ll bring the point of view.</em></h2><a class="button" href="mailto:contact@ampersyn.com?subject=Let%27s%20talk%20about%20${encodeURIComponent(s.title)}">Start a conversation ↗</a></div></section></main>${footer()}`}
const service=services[document.body.dataset.service];if(service)document.getElementById('app').innerHTML=servicePage(service);
